## YAML Template.
---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/
    username: postgres    
    password: 123 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true  
    hibernate:
      ddl-auto: update
    
server:
    port: 9080
    servlet:
        context-path: /pradoph
        
logging:
   level: 
      # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error 
      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN  